apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Chart.Name}}-configmap"
  namespace: {{.Values.app.namespace}}
data:
  default.conf: |-
    server {
      listen 80;
      server_name localhost;
      root /usr/share/nginx/html;
      index index.html index.htm;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location ~* \.(?:css|js)$ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
      }

      location ~ ^.+\..+$ {
        try_files $uri =404;
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }
